//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AvlSeats
    {
        public int Avlid { get; set; }
        public int BusId { get; set; }
        public Nullable<int> Available { get; set; }
        public int Capacity { get; set; }
    
        public virtual T_BusDetails T_BusDetails { get; set; }
    }
}
