//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_JourneyDetails
    {
        public T_JourneyDetails()
        {
            this.T_ReservationDetails = new HashSet<T_ReservationDetails>();
        }
    
        public int JourneyId { get; set; }
        public int BusId { get; set; }
        public int RouteId { get; set; }
        public System.TimeSpan DepartureTime { get; set; }
        public System.TimeSpan ArrivalTime { get; set; }
        public int JourneyFare { get; set; }
    
        public virtual T_RouteDetail T_RouteDetail { get; set; }
        public virtual T_BusDetails T_BusDetails { get; set; }
        public virtual ICollection<T_ReservationDetails> T_ReservationDetails { get; set; }
    }
}
