//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ReservationDetails
    {
        public int ReserveId { get; set; }
        public int UserId { get; set; }
        public int JourneyId { get; set; }
        public System.DateTime ReserveDate { get; set; }
        public int NoOfSeat { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public int Amount { get; set; }
    
        public virtual T_JourneyDetails T_JourneyDetails { get; set; }
        public virtual T_Users T_Users { get; set; }
    }
}
