//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_RouteDetail
    {
        public T_RouteDetail()
        {
            this.T_JourneyDetails = new HashSet<T_JourneyDetails>();
        }
    
        public int RouteId { get; set; }
        public int RouteDistance { get; set; }
        public string FromId { get; set; }
        public string ToId { get; set; }
    
        public virtual ICollection<T_JourneyDetails> T_JourneyDetails { get; set; }
    }
}
